import Foundation

public protocol Game: AnyObject {
    associatedtype Options: GameOptions
    
    static var requiredPlayerCount: ClosedRange<Int> { get }
    
    /// Initialize `players` from the given `savedPlayers`. If the provided options are invalid, throw `HostError.validationFailed`.
    init(savedPlayers: [SavedPlayer], options: Options) throws
    /// The first ambient action sent to the game.
    func initialAction() -> any GameAction
    /// Handle the action in the given `context`.
    func handle(context: GameActionContext) throws
    /// Called when a game is closed. Implement this method to release any cyclic references and avoid memory leaks.
    func close()
}

extension Game {
    
    /// Converts the given `options` string to the `Options` type and then calls `init(players:options:)`.
    public static func from(savedGame: SavedGame) throws -> Self {
        if !Self.requiredPlayerCount.contains(savedGame.players.count) {
            throw HostError(message: "Unsupported number of players.")
        }
        if Set(savedGame.players.map({ $0.id })).count < savedGame.players.count {
            throw HostError(message: "Duplicate player ids.")
        }
        let options = try RequestCoder.decode(Options.self, from: Data(savedGame.options.utf8))
        try options.validate()
        return try Self.init(savedPlayers: savedGame.players, options: options)
    }
    
    public func close() {
    }
    
}

public protocol GameOptions: Codable {
    init()
    func validate() throws
}

extension GameOptions {
    
    init(data: String) throws {
        self = try RequestCoder.decode(Self.self, from: Data(data.utf8))
    }
    
    public func validate() throws {
    }
    
    public func encoded() -> String {
        return String(decoding: RequestCoder.encode(self), as: UTF8.self)
    }
    
}

public protocol GamePlayer: AnyObject, Hashable, Identifiable {
    var id: UUID { get }
}

extension GamePlayer {
    
    public static func == (lhs: Self, rhs: Self) -> Bool {
        return lhs === rhs
    }
    
    public func hash(into hasher: inout Hasher) {
        ObjectIdentifier(self).hash(into: &hasher)
    }
    
}

/// A request type that represents a game action, generated either by a player or by the game itself.
public protocol GameAction: Request {
}

/// Implemented by games that support one or more game bot strategies.
public protocol GameBot: Game {
    associatedtype Strategy: GameStrategy
    
    /// Called when a bot needs to choose its next action. Return `nil` if the bot is waiting.
    func action(for player: UUID, strategy: Strategy) throws -> (any GameAction)?
}

public protocol GameStrategy: CaseIterable, RawRepresentable where RawValue == String {
}

/// Implemented by games that can generate ambient actions that are not immediate consequence of a user action, e.g. when generated by a timer.
public protocol AsyncGame: Game {
    var asyncActionHandler: AsyncGameActionHandler? { get set }
}

public protocol AsyncGameActionHandler {
    func handleAsyncGameAction(player: UUID?, action: any GameAction)
}

extension AsyncGameActionHandler {
    
    public func handleAsyncGameAction(player: UUID? = nil, action: any GameAction) {
        handleAsyncGameAction(player: player, action: action)
    }
    
}
